### ISSUE TITLE
Env Viz: frame not shown

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#1825]
<img width="553" alt="Screenshot 2021-06-25 at 12 28 21 PM" src="https://user-images.githubusercontent.com/30220768/123373949-e190e400-d5b8-11eb-8089-291e81af5d53.png">

The program:
https://share.sourceacademy.nus.edu.sg/sumofsquaresbug

**Comment by mark-friedman** [comment]
Is it possible that this is the result of tail-call optimization?  I ask because I also tried to demonstrate the environments create by fact_iter (in [this program](https://share.sourceacademy.nus.edu.sg/badfactiter)), where a similar problem occurs and is the more-or-less canonical case for tail-call optimization.

This all brings up an interesting pedagogical question.  In [section 3.2.1](https://sourceacademy.org/sicpjs/3.2.1), the book provides a description of how environments are created during function application which doesn't take into account tail-call optimization.  It would be tempting then to fix the current issue by disabling tail-call optimization, at least when breakpoints have been set.  However, the book has also already discussed iterative processes in [section 1.2.1](https://sourceacademy.org/sicpjs/1.2.1), so astute students might wonder why there would be a proliferation of environment frames for an iterative process!

Note that an alternate fix of adding the single new frame for tail-calls, so there would at least be **a** frame created for the application of `sum-of-squares` or `fact_iter`, and reusing it for recursive calls has the pedagogical problem that it doesn't strictly match the description given in [section 3.2.1](https://sourceacademy.org/sicpjs/3.2.1).  This is a problem with the book, though, and I'm not sure what the best course of action would be.

![Screen Shot 2021-06-25 at 9 57 27 AM](https://user-images.githubusercontent.com/1743690/123459987-d7142180-d59b-11eb-9e06-432b22a1714c.png)

**Comment by martin-henz** [comment]
Nice catch @mark-friedman . I just looked up the original SICP (2nd edition). SICP's approach is to silently ignore the requirement that iterative processes should require constant space. This comes out on SICP in figure 3.11 page 249 where there is a tail-recursive call 
```
(sqrt-iter 1.0))
```
which gets its frame like any other call.

We follow SICP in SICP JS: https://sicp.sourceacademy.org/sicpjs.pdf
see figure 3.11  on page 223.

In a similar situation in section 4.1, we have added a footnote: Footnote 6 on SICP JS page 332. I'll discuss with the SICP JS team if we should add a similar footnote  in 3.2.4.

What this means for the Environment Visualizer: You are right @mark-friedman : We should disable tail calls in the interpreter that underlies the environment visualizer.

**Comment by martin-henz** [comment]
@CrownKira found a nice fix for this in https://github.com/source-academy/js-slang/pull/1020
A one-line change in the interpreter makes sure that the environment visualizer keeps track of the frame even though the underlying interpreter is tail-recursive.

**Comment by martin-henz** [comment]
> Nice catch @mark-friedman . I just looked up the original SICP (2nd edition). SICP's approach is to silently ignore the requirement that iterative processes should require constant space. This comes out on SICP in figure 3.11 page 249 where there is a tail-recursive call
> 
> ```
> (sqrt-iter 1.0)
> ```
> 
> which gets its frame like any other call.
> 
> We follow SICP in SICP JS: https://sicp.sourceacademy.org/sicpjs.pdf
> see figure 3.11 on page 223.
> 
> In a similar situation in section 4.1, we have added a footnote: Footnote 6 on SICP JS page 332. I'll discuss with the SICP JS team if we should add a similar footnote in 3.2.4.
> 
> What this means for the Environment Visualizer: You are right @mark-friedman : We should disable tail calls in the interpreter that underlies the environment visualizer.

A followup on this: Thinking about it again, I feel that we should not add a footnote in 3.2.4. The environment model doesn't say how exactly functions return their results. It is conceivable that we have a mechanism that returns results nonchronologically, and thereby making intermediate frames redundant. Indeed, that's what our implementation does!

My conclusion: The environment model operates at a level of abstraction that is too high for a discussion of the iterative/recursive processes.

**Comment by martin-henz** [comment]
To complete the discussion: The fact that tail recursion cannot be discussed at the level of the environment model is explained in a footnote in 3.2.2:
https://sourceacademy.org/sicpjs/3.2.2#footnote-1

The beginning of chapter 5 mentions this, too:
https://sourceacademy.org/sicpjs/5#p1

**Comment by mark-friedman** [comment]
I agree that the SICP JS is consistent with SICP on this issue.  I think that maybe SICP makes too big a deal early on of introducing iterative processes and TCO in section 1.2.1, before students really have a coherent model of how it works.  Just my opinion, though.

**Comment by martin-henz** [comment]
1.2.1 doesn't explain iterative/recursive processes in terms of TCO. It uses the concept of a deferred operation. I think this makes sense. Tail recursion is discussed in chapter 5.

**Comment by mark-friedman** [comment]
1.2.1 does talk about tail recursion in the paragraph starting with:
> One reason that the distinction between process and function may be confusing ...
and in the footnotes referred to within.

My point is simply that I think the authors could have deferred the discussion of iterative and recursive processes until later in the book, or at least been a bit clearer in the discussion of the environment model in chapter 3 of how it relates to the issues of tail recursion, deferred operations and iterative/recursive processes.  The footnote there that says:
>The environment model will not clarify our claim in section 1.2.1 that the interpreter can execute a function such as fact_iter in a constant amount of space using tail recursion.

is a somewhat vague.  To me, not only does the environment model not clarify that claim, it appears, at least on the surface, to support the contrary of the claim.  I would love to have seen an explicit statement similar to yours where you say:

>The environment model operates at a level of abstraction that is too high for a discussion of the iterative/recursive processes.

That said, none of this directly has to do with this bug.  It's just a discussion about the book and my teaching with the book.  Thanks for indulging me.
