### ISSUE TITLE
Assessment Workspace line highlighting crashes frontend

### ISSUE THREAD

**Issue by chownces** [source-academy/frontend#2284]
Bug introduced in #2282. Only occurs in assessments where the AceEditor is being used

![image](https://user-images.githubusercontent.com/53928333/207666785-7a1800eb-6089-4072-a5e2-127f76bb3746.png)

**Comment by ianyong** [comment]
Now that `WorkspaceState` contains nested state in the form of the editor tabs array, the `RESET_WORKSPACE` and `UPDATE_WORKSPACE` no longer satisfy some of the use cases since we can no longer partially update nested state. I will probably have to introduce new actions just for (partially) updating a specified editor tab.

As @chownces mentioned, this doesn't affect the public version of the Source Academy, so I will PR the fix tomorrow when I'm more awake.
