### ISSUE TITLE
Expired refresh token does not sign the user out

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/frontend#2469]
As discussed with @chownces @YaleChen299 @shenyih0ng  last winter:

For SA@X deployments, the user is not automatically signed out after the token expires. Instead, the user gets a lot of 401 popup notifications and they would have to manually log out.

**Comment by chownces** [comment]
Refer to #2100 for more context. As previously discussed with the profs, we should account for the case where the user has unsaved work on refresh token expiry. We should allow the user to copy their work first instead of forcing a logout immediately, which would redirect them to the login page.

**Comment by vansh284** [comment]
@chownces Could you provide some elaboration? 

From my understanding https://github.com/source-academy/frontend/issues/2100 seemed to be concerned about cases where the user's refresh token was valid but he/she was auto-logged out by other background requests which returned a 401/403. 

I may be missing some context regarding your discussions, what would be some cases where the user has unsaved work after refresh token expiry i.e. 1 week of not logging in?

Also, wouldn't the expired refresh token make the users unable to save their work since the backend authentication fails? (not 100% sure about this because I'm not too familiar with our backend).

**Comment by RichDom2185** [comment]
> what would be some cases where the user has unsaved work after refresh token expiry i.e. 1 week of not logging in?

E.g. A user opens a mission, works on it without saving/submitting, closes their laptop for the night (leaving their browser tab open), only to come back to it tomorrow and realise that they can't submit because their access token happens to have expired overnight.

> wouldn't the expired refresh token make the users unable to save their work since the backend authentication fails?

Correct. What #2100 is trying to say by "saving their work" is the user and copy whatever code they need elsewhere (or simply sign in from another browser tab) and submit that way, retaining all their work. If we log the user out immediately (and redirect to login page) the user would lose all the work they have done since the last save point.
