### ISSUE TITLE
CSE machine: jumping function objects

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2700]
Function objects jump too much. Example: https://share.sourceacademy.org/ljoin
<img width="347" alt="Screenshot 2023-10-24 at 9 25 27 AM" src="https://github.com/source-academy/frontend/assets/30220768/46ff0ffe-6a01-4ead-9a99-099ab38380dc">
<img width="347" alt="Screenshot 2023-10-24 at 9 25 52 AM" src="https://github.com/source-academy/frontend/assets/30220768/7a4fd769-ddb3-47e2-9658-73fe16c1b822">

**Comment by CZX123** [comment]
I've looked into the code and found that the reason this happens is because the different environment frames are drawn one at a time, and within each frame, the bindings and corresponding values (functions, arrays, etc.) are drawn before the next frame even exists.

So in this example, the function `y => 0` is drawn at the program frame because at that moment in time, that is the only binding that exists in the entire program.

A solution to this would be to change the drawing order of values and draw them after all frames and their bindings have been drawn first.

**Comment by CZX123** [comment]
Actually, I've found that this issue also applies to other non-primitive objects like arrays/pairs, and I think this issue should be postponed until js-slang gives us more information on which frame each object is supposed to belong to.

In fact, this issue should be solved together with issue #2705.
